import { Blocker } from '@/types';

export const BLOCKERS: Blocker[] = [
  {
    id: 'bl-1',
    projectId: 'proj-11',
    taskId: 't-60',
    title: 'PayU API credentials not received',
    description: 'Waiting for PayU merchant account credentials from client. Integration cannot proceed without sandbox and production API keys.',
    reportedById: 'w-65',
    teamId: 'team-6',
    createdDate: '2026-08-28T10:30:00Z',
    status: 'OPEN',
  },
  {
    id: 'bl-2',
    projectId: 'proj-3',
    taskId: 't-22',
    title: 'Client data schema not finalized',
    description: 'CRM import module is blocked because the client has not provided a finalized data schema for the legacy system export. Affects bulk import implementation.',
    reportedById: 'w-42',
    teamId: 'team-3',
    createdDate: '2026-08-25T09:00:00Z',
    status: 'OPEN',
  },
  {
    id: 'bl-3',
    projectId: 'proj-4',
    taskId: 't-27',
    title: 'ERP vendor not providing API documentation',
    description: 'The third-party ERP vendor (LogiStar) has not provided comprehensive API documentation for integration adapters. Multiple follow-ups have been sent.',
    reportedById: 'w-10',
    teamId: 'team-1',
    createdDate: '2026-08-22T14:00:00Z',
    status: 'OPEN',
  },
  {
    id: 'bl-4',
    projectId: 'proj-7',
    taskId: 't-45',
    title: 'Compliance review pending from legal team',
    description: 'Audit log requirements need sign-off from the client\'s legal and compliance team before implementation can begin. Awaiting response for 6 business days.',
    reportedById: 'w-32',
    teamId: 'team-2',
    createdDate: '2026-08-20T11:00:00Z',
    status: 'OPEN',
  },
  {
    id: 'bl-5',
    projectId: 'proj-3',
    taskId: 't-20',
    title: 'Production email server SSL certificate issue',
    description: 'Email integration is failing on the staging environment due to an SSL certificate mismatch on the client\'s mail server. DevOps involvement needed.',
    reportedById: 'w-35',
    teamId: 'team-3',
    createdDate: '2026-08-27T16:30:00Z',
    status: 'OPEN',
  },
  {
    id: 'bl-6',
    projectId: 'proj-1',
    taskId: 't-7',
    title: 'POS hardware delivery delayed',
    description: 'Physical POS terminals ordered for integration testing have not been delivered. Vendor cites supply chain issues. ETA extended to September 10.',
    reportedById: 'w-2',
    teamId: 'team-1',
    createdDate: '2026-08-15T10:00:00Z',
    status: 'OPEN',
  },
  {
    id: 'bl-7',
    projectId: 'proj-8',
    taskId: 't-47',
    title: 'Figma access not granted to all designers',
    description: 'Three team members are waiting for Figma Enterprise license seats. This is blocking component finalization and handoff.',
    reportedById: 'w-52',
    teamId: 'team-4',
    createdDate: '2026-08-29T09:15:00Z',
    status: 'OPEN',
  },
  {
    id: 'bl-8',
    projectId: 'proj-9',
    taskId: 't-52',
    title: 'Knowledge base content not received from client',
    description: 'Client was supposed to provide existing FAQ and support documentation for migration into the knowledge base. No content received after 3 requests.',
    reportedById: 'w-11',
    teamId: 'team-1',
    createdDate: '2026-08-26T13:00:00Z',
    status: 'OPEN',
  },
  // Resolved blockers
  {
    id: 'bl-r1',
    projectId: 'proj-2',
    title: 'OTA API rate limiting issue',
    description: 'Channel manager integration was hitting rate limits on the OTA API. Resolved by implementing exponential backoff and request queuing.',
    reportedById: 'w-19',
    teamId: 'team-2',
    createdDate: '2026-07-10T09:00:00Z',
    resolvedDate: '2026-07-18T15:00:00Z',
    status: 'RESOLVED',
  },
  {
    id: 'bl-r2',
    projectId: 'proj-6',
    title: 'AWS account quota increase pending',
    description: 'EC2 instance quota increase was needed for load testing environment. Resolved after AWS support approved the quota increase.',
    reportedById: 'w-54',
    teamId: 'team-5',
    createdDate: '2026-06-15T10:00:00Z',
    resolvedDate: '2026-06-22T12:00:00Z',
    status: 'RESOLVED',
  },
];
