import { Notification } from '@/types';

const now = new Date('2026-08-30T14:00:00Z');
function minsAgo(m: number) { return new Date(now.getTime() - m * 60000).toISOString(); }
function hoursAgo(h: number) { return minsAgo(h * 60); }
function daysAgo(d: number) { return hoursAgo(d * 24); }

export const NOTIFICATIONS: Notification[] = [
  {
    id: 'notif-1',
    type: 'BLOCKER',
    title: 'New blocker reported on Payment Gateway Integration',
    description: 'Isha Sharma reported: PayU API credentials not received from client. Integration on hold.',
    projectId: 'proj-11',
    read: false,
    timestamp: minsAgo(60),
    priority: 'HIGH',
  },
  {
    id: 'notif-2',
    type: 'PROJECT_ALERT',
    title: 'CRM Development is at risk of missing deadline',
    description: 'Project is 28% complete with 30 days remaining. Progress is significantly below target.',
    projectId: 'proj-3',
    read: false,
    timestamp: hoursAgo(2),
    priority: 'HIGH',
  },
  {
    id: 'notif-3',
    type: 'DEADLINE',
    title: 'Client Portal deadline in 45 days',
    description: 'Project deadline is October 15. Current progress is 41%. Risk of delay if blockers are not resolved.',
    projectId: 'proj-7',
    read: false,
    timestamp: hoursAgo(3),
    priority: 'MEDIUM',
  },
  {
    id: 'notif-4',
    type: 'BLOCKER',
    title: 'Blocker unresolved for 8 days — ERP API documentation',
    description: 'The third-party ERP vendor integration blocker on Workflow Automation Platform remains unresolved after 8 days.',
    projectId: 'proj-4',
    read: false,
    timestamp: hoursAgo(5),
    priority: 'HIGH',
  },
  {
    id: 'notif-5',
    type: 'TEAM_UPDATE',
    title: 'Backend Engineering team workload is high',
    description: 'Backend team has 28 active tasks across 3 projects. Consider reviewing workload distribution.',
    read: false,
    timestamp: hoursAgo(6),
    priority: 'MEDIUM',
  },
  {
    id: 'notif-6',
    type: 'PROJECT_ALERT',
    title: 'Design System project past deadline',
    description: 'Design System & Component Library project deadline was August 31. Current progress is 44%.',
    projectId: 'proj-8',
    read: false,
    timestamp: daysAgo(1),
    priority: 'HIGH',
  },
  {
    id: 'notif-7',
    type: 'BLOCKER',
    title: 'Compliance review blocking Client Portal progress',
    description: 'Audit log module is blocked pending legal sign-off. Progress halted for 6 days.',
    projectId: 'proj-7',
    read: true,
    timestamp: daysAgo(1),
    priority: 'MEDIUM',
  },
  {
    id: 'notif-8',
    type: 'DEADLINE',
    title: 'Payment Gateway Integration deadline in 62 days',
    description: 'Project deadline is October 31. Multiple blockers currently open. Priority: CRITICAL.',
    projectId: 'proj-11',
    read: true,
    timestamp: daysAgo(2),
    priority: 'HIGH',
  },
  {
    id: 'notif-9',
    type: 'TEAM_UPDATE',
    title: 'QA Team assigned to CRM & Inventory simultaneously',
    description: 'QA team is currently running parallel testing on 2 projects. Monitor for capacity issues.',
    read: true,
    timestamp: daysAgo(2),
    priority: 'LOW',
  },
  {
    id: 'notif-10',
    type: 'SYSTEM',
    title: 'Weekly workforce summary ready',
    description: 'The weekly workforce report has been compiled. 284 tasks completed this month across all projects.',
    read: true,
    timestamp: daysAgo(3),
    priority: 'LOW',
  },
  {
    id: 'notif-11',
    type: 'PROJECT_ALERT',
    title: 'Workflow Automation Platform progress behind schedule',
    description: 'Project is 18% complete. Expected target was 30% by end of August. Supervisor review recommended.',
    projectId: 'proj-4',
    read: true,
    timestamp: daysAgo(3),
    priority: 'HIGH',
  },
  {
    id: 'notif-12',
    type: 'SYSTEM',
    title: 'New project added: Kubernetes Orchestration Setup',
    description: 'Vikram Patil has been assigned as supervisor for the new Kubernetes setup project for DataVault Technologies.',
    projectId: 'proj-12',
    read: true,
    timestamp: daysAgo(5),
    priority: 'LOW',
  },
];
