import { ProjectViewModel } from '@/types';

export const INITIAL_PROJECTS: ProjectViewModel[] = [
  // ── ACTIVE / ON_TRACK ──
  {
    id: 'proj-1',
    name: 'Hotel Billing System',
    client: 'Grand Hotels & Resorts',
    description: 'A comprehensive billing, invoicing, and payment management system for a luxury hotel chain. Includes POS integration, GST compliance, and automated reporting.',
    startDate: '2026-01-10',
    deadline: '2026-10-31',
    priority: 'HIGH',
    supervisorId: 'sup-1',
    status: 'ACTIVE',
    health: 'ON_TRACK',
    progress: 76,
    teamCount: 2,
    createdAt: '2026-01-05T09:00:00Z',
  },
  {
    id: 'proj-2',
    name: 'Resort Management Platform',
    client: 'Seaside Resorts Pvt Ltd',
    description: 'End-to-end resort operations management — reservations, room management, housekeeping, spa, F&B, and guest portal.',
    startDate: '2026-03-01',
    deadline: '2026-12-15',
    priority: 'MEDIUM',
    supervisorId: 'sup-2',
    status: 'ACTIVE',
    health: 'ON_TRACK',
    progress: 48,
    teamCount: 2,
    createdAt: '2026-02-20T09:00:00Z',
  },
  {
    id: 'proj-5',
    name: 'Employee Self-Service Portal',
    client: 'Meridian Enterprises',
    description: 'A modern employee self-service portal covering leave management, payslips, HR requests, and company announcements.',
    startDate: '2026-04-15',
    deadline: '2026-09-30',
    priority: 'MEDIUM',
    supervisorId: 'sup-4',
    status: 'ACTIVE',
    health: 'ON_TRACK',
    progress: 62,
    teamCount: 2,
    createdAt: '2026-04-10T09:00:00Z',
  },
  {
    id: 'proj-6',
    name: 'Cloud Infrastructure Migration',
    client: 'DataVault Technologies',
    description: 'Migrate on-premise infrastructure to AWS cloud — EC2, RDS, S3, CloudFront, and CI/CD pipeline setup with zero-downtime deployment.',
    startDate: '2026-05-01',
    deadline: '2026-11-30',
    priority: 'HIGH',
    supervisorId: 'sup-5',
    status: 'ACTIVE',
    health: 'ON_TRACK',
    progress: 55,
    teamCount: 1,
    createdAt: '2026-04-25T09:00:00Z',
  },
  {
    id: 'proj-9',
    name: 'Customer Support Platform',
    client: 'Nexus Retail Solutions',
    description: 'Omnichannel customer support platform with ticketing, live chat, knowledge base, and SLA management.',
    startDate: '2026-02-15',
    deadline: '2026-11-15',
    priority: 'MEDIUM',
    supervisorId: 'sup-1',
    status: 'ACTIVE',
    health: 'ON_TRACK',
    progress: 58,
    teamCount: 1,
    createdAt: '2026-02-10T09:00:00Z',
  },
  {
    id: 'proj-10',
    name: 'Inventory Management System',
    client: 'SupplyChain Pro',
    description: 'Real-time inventory tracking, reorder automation, supplier management, and warehouse optimization system.',
    startDate: '2026-06-01',
    deadline: '2026-12-31',
    priority: 'HIGH',
    supervisorId: 'sup-3',
    status: 'ACTIVE',
    health: 'ON_TRACK',
    progress: 32,
    teamCount: 1,
    createdAt: '2026-05-25T09:00:00Z',
  },

  // ── ACTIVE / AT_RISK ──
  {
    id: 'proj-4',
    name: 'Workflow Automation Platform',
    client: 'Logistics Pro Ltd',
    description: 'No-code/low-code workflow automation platform for logistics operations — approvals, routing, notifications, and integration with third-party ERPs.',
    startDate: '2026-06-01',
    deadline: '2026-11-30',
    priority: 'HIGH',
    supervisorId: 'sup-1',
    status: 'ACTIVE',
    health: 'AT_RISK',
    progress: 18,
    teamCount: 2,
    createdAt: '2026-05-20T09:00:00Z',
  },
  {
    id: 'proj-7',
    name: 'Client Portal & Dashboard',
    client: 'Prestige Financial Services',
    description: 'Secure client-facing portal for financial services — account overview, document upload, statement downloads, and advisor communication.',
    startDate: '2026-04-01',
    deadline: '2026-10-15',
    priority: 'HIGH',
    supervisorId: 'sup-2',
    status: 'ACTIVE',
    health: 'AT_RISK',
    progress: 41,
    teamCount: 2,
    createdAt: '2026-03-25T09:00:00Z',
  },
  {
    id: 'proj-11',
    name: 'Payment Gateway Integration',
    client: 'QuickPay Systems',
    description: 'Integrate multiple payment gateways (Razorpay, PayU, Stripe) with unified API, reconciliation dashboard, and automated refund processing.',
    startDate: '2026-07-01',
    deadline: '2026-10-31',
    priority: 'CRITICAL',
    supervisorId: 'sup-4',
    status: 'ACTIVE',
    health: 'AT_RISK',
    progress: 22,
    teamCount: 1,
    createdAt: '2026-06-25T09:00:00Z',
  },

  // ── ACTIVE / DELAYED ──
  {
    id: 'proj-3',
    name: 'CRM Development',
    client: 'TechCorp Solutions',
    description: 'Enterprise CRM system — contact management, deal pipeline, activity tracking, email integration, and analytics reporting.',
    startDate: '2026-05-01',
    deadline: '2026-09-30',
    priority: 'CRITICAL',
    supervisorId: 'sup-3',
    status: 'ACTIVE',
    health: 'DELAYED',
    progress: 28,
    teamCount: 1,
    createdAt: '2026-04-20T09:00:00Z',
  },
  {
    id: 'proj-8',
    name: 'Design System & Component Library',
    client: 'Internal',
    description: 'Build Apex\'s internal design system — Figma component library, React component library, documentation site, and usage guidelines.',
    startDate: '2026-03-15',
    deadline: '2026-08-31',
    priority: 'MEDIUM',
    supervisorId: 'sup-4',
    status: 'ACTIVE',
    health: 'DELAYED',
    progress: 44,
    teamCount: 2,
    createdAt: '2026-03-10T09:00:00Z',
  },

  // ── PLANNED ──
  {
    id: 'proj-12',
    name: 'Kubernetes Orchestration Setup',
    client: 'DataVault Technologies',
    description: 'Set up Kubernetes cluster for container orchestration, autoscaling, monitoring with Prometheus/Grafana, and GitOps with ArgoCD.',
    startDate: '2026-09-01',
    deadline: '2026-12-31',
    priority: 'HIGH',
    supervisorId: 'sup-5',
    status: 'PLANNED',
    health: 'ON_TRACK',
    progress: 0,
    teamCount: 1,
    createdAt: '2026-08-01T09:00:00Z',
  },

  // ── COMPLETED ──
  {
    id: 'proj-c1',
    name: 'HR Management System',
    client: 'Acme Corp',
    description: 'Complete HR management system covering recruitment, onboarding, performance reviews, and payroll.',
    startDate: '2025-06-01',
    deadline: '2026-02-28',
    priority: 'HIGH',
    supervisorId: 'sup-2',
    status: 'COMPLETED',
    health: 'ON_TRACK',
    progress: 100,
    teamCount: 3,
    createdAt: '2025-05-20T09:00:00Z',
  },
  {
    id: 'proj-c2',
    name: 'E-Commerce Platform',
    client: 'ShopEase India',
    description: 'Multi-vendor e-commerce platform with product catalog, cart, payments, and order management.',
    startDate: '2025-03-01',
    deadline: '2025-12-31',
    priority: 'CRITICAL',
    supervisorId: 'sup-1',
    status: 'COMPLETED',
    health: 'ON_TRACK',
    progress: 100,
    teamCount: 4,
    createdAt: '2025-02-15T09:00:00Z',
  },
  {
    id: 'proj-c3',
    name: 'Attendance & Payroll Integration',
    client: 'Pinnacle Industries',
    description: 'Biometric attendance integration with payroll calculation, leave management, and statutory compliance.',
    startDate: '2025-09-01',
    deadline: '2026-03-31',
    priority: 'MEDIUM',
    supervisorId: 'sup-3',
    status: 'COMPLETED',
    health: 'ON_TRACK',
    progress: 100,
    teamCount: 2,
    createdAt: '2025-08-20T09:00:00Z',
  },
];
