from app.models.user import UserRoleEnum
from app.authorization.permissions import Permission

ROLE_PERMISSIONS = {
    UserRoleEnum.OWNER: {
        Permission.ORGANIZATION_VIEW,
        Permission.ORGANIZATION_UPDATE,
        Permission.OWNER_VIEW,
        Permission.OWNER_CREATE,
        Permission.OWNER_UPDATE,
        Permission.OWNER_DEACTIVATE,
        Permission.SUPERVISOR_VIEW,
        Permission.SUPERVISOR_CREATE,
        Permission.SUPERVISOR_UPDATE,
        Permission.SUPERVISOR_DEACTIVATE,
        Permission.TEAM_VIEW,
        Permission.TEAM_CREATE,
        Permission.TEAM_UPDATE,
        Permission.TEAM_DELETE,
        Permission.TEAM_MEMBERS_MANAGE,
        Permission.PROJECT_VIEW,
        Permission.PROJECT_CREATE,
        Permission.PROJECT_UPDATE,
        Permission.PROJECT_DELETE,
        Permission.PROJECT_ASSIGN,
        Permission.WORKER_VIEW,
        Permission.WORKER_CREATE,
        Permission.WORKER_UPDATE,
        Permission.WORKER_DEACTIVATE,
        Permission.TASK_VIEW,
        Permission.TASK_CREATE,
        Permission.TASK_UPDATE,
        Permission.TASK_DELETE,
        Permission.REPORT_VIEW,
        Permission.REPORT_EXPORT,
        Permission.REPORT_ORGANIZATION_VIEW,
        Permission.REPORT_ORGANIZATION_EXPORT,
        Permission.ANALYTICS_VIEW,
        Permission.INTELLIGENCE_VIEW,
    },
    UserRoleEnum.SUPERVISOR: {
        Permission.ORGANIZATION_VIEW,
        Permission.SUPERVISOR_VIEW,
        Permission.SUPERVISOR_UPDATE,
        Permission.TEAM_VIEW,
        Permission.TEAM_CREATE,
        Permission.TEAM_UPDATE,
        Permission.TEAM_MEMBERS_MANAGE,
        Permission.PROJECT_VIEW,
        Permission.PROJECT_CREATE,
        Permission.PROJECT_UPDATE,
        Permission.PROJECT_ASSIGN,
        Permission.WORKER_VIEW,
        Permission.WORKER_CREATE,
        Permission.WORKER_UPDATE,
        Permission.WORKER_DEACTIVATE,
        Permission.TASK_VIEW,
        Permission.TASK_CREATE,
        Permission.TASK_UPDATE,
        Permission.TASK_DELETE,
        Permission.REPORT_VIEW,
        Permission.REPORT_EXPORT,
        Permission.ANALYTICS_VIEW,
    },
    UserRoleEnum.TEAM_LEADER: {
        Permission.ORGANIZATION_VIEW,
        Permission.SUPERVISOR_VIEW,
        Permission.TEAM_VIEW,
        Permission.TEAM_MEMBERS_MANAGE,
        Permission.PROJECT_VIEW,
        Permission.WORKER_VIEW,
        Permission.WORKER_CREATE, # As per spec, they can add workers to team if permitted
        Permission.WORKER_UPDATE,
        Permission.TASK_VIEW,
        Permission.TASK_CREATE,
        Permission.TASK_UPDATE,
        Permission.TASK_DELETE,
        Permission.REPORT_VIEW,
        Permission.REPORT_EXPORT,
        # ANALYTICS_VIEW intentionally excluded — team leaders see per-team data
        # through project/task scoping, not org-level analytics dashboards.
    },
    UserRoleEnum.WORKER: {
        Permission.ORGANIZATION_VIEW,
        Permission.TEAM_VIEW,
        Permission.PROJECT_VIEW,
        Permission.WORKER_VIEW,
        Permission.WORKER_UPDATE, # Update self
        Permission.TASK_VIEW,
        Permission.TASK_UPDATE,
        Permission.REPORT_VIEW, # Limited to own data
        # ANALYTICS_VIEW intentionally excluded — workers access their own task data
        # through the workforce view, not org-level analytics dashboards.
    },
}
