"""Add TaskTransition

Revision ID: 49c68e298daa
Revises: 987e1ddf1ae1
Create Date: 2026-09-08 14:30:33.904703

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49c68e298daa'
down_revision: Union[str, None] = '987e1ddf1ae1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_transitions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('from_status', sa.Enum('TODO', 'IN_PROGRESS', 'COMPLETED', 'BLOCKED', name='task_status_enum'), nullable=True),
    sa.Column('to_status', sa.Enum('TODO', 'IN_PROGRESS', 'COMPLETED', 'BLOCKED', name='task_status_enum'), nullable=False),
    sa.Column('changed_by_user_id', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_transitions_changed_by_user_id'), 'task_transitions', ['changed_by_user_id'], unique=False)
    op.create_index(op.f('ix_task_transitions_id'), 'task_transitions', ['id'], unique=False)
    op.create_index(op.f('ix_task_transitions_task_id'), 'task_transitions', ['task_id'], unique=False)
    op.create_index(op.f('ix_task_transitions_timestamp'), 'task_transitions', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_transitions_timestamp'), table_name='task_transitions')
    op.drop_index(op.f('ix_task_transitions_task_id'), table_name='task_transitions')
    op.drop_index(op.f('ix_task_transitions_id'), table_name='task_transitions')
    op.drop_index(op.f('ix_task_transitions_changed_by_user_id'), table_name='task_transitions')
    op.drop_table('task_transitions')
    # ### end Alembic commands ###
