"""report schedules

Revision ID: c44abb9df33c
Revises: 49c68e298daa
Create Date: 2026-09-11 15:16:08.905537

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c44abb9df33c'
down_revision: Union[str, None] = '49c68e298daa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_schedules',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('report_type', sa.Enum('ORGANIZATION', 'PROJECT', 'WORKER', 'TEAM', 'ACTIVITY', name='report_type_enum'), nullable=False),
    sa.Column('scope_id', sa.String(), nullable=True),
    sa.Column('export_format', sa.Enum('CSV', 'XLSX', 'PDF', name='report_format_enum'), nullable=False),
    sa.Column('frequency', sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', name='report_frequency_enum'), nullable=False),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_user_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_schedules_created_by_user_id'), 'report_schedules', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_report_schedules_id'), 'report_schedules', ['id'], unique=False)
    op.create_index(op.f('ix_report_schedules_is_active'), 'report_schedules', ['is_active'], unique=False)
    op.create_index(op.f('ix_report_schedules_next_run_at'), 'report_schedules', ['next_run_at'], unique=False)
    op.create_index(op.f('ix_report_schedules_report_type'), 'report_schedules', ['report_type'], unique=False)
    op.create_table('report_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('schedule_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='report_run_status_enum'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('output_filename', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['schedule_id'], ['report_schedules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_runs_created_at'), 'report_runs', ['created_at'], unique=False)
    op.create_index(op.f('ix_report_runs_id'), 'report_runs', ['id'], unique=False)
    op.create_index(op.f('ix_report_runs_schedule_id'), 'report_runs', ['schedule_id'], unique=False)
    op.create_index(op.f('ix_report_runs_status'), 'report_runs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_report_runs_status'), table_name='report_runs')
    op.drop_index(op.f('ix_report_runs_schedule_id'), table_name='report_runs')
    op.drop_index(op.f('ix_report_runs_id'), table_name='report_runs')
    op.drop_index(op.f('ix_report_runs_created_at'), table_name='report_runs')
    op.drop_table('report_runs')
    op.drop_index(op.f('ix_report_schedules_report_type'), table_name='report_schedules')
    op.drop_index(op.f('ix_report_schedules_next_run_at'), table_name='report_schedules')
    op.drop_index(op.f('ix_report_schedules_is_active'), table_name='report_schedules')
    op.drop_index(op.f('ix_report_schedules_id'), table_name='report_schedules')
    op.drop_index(op.f('ix_report_schedules_created_by_user_id'), table_name='report_schedules')
    op.drop_table('report_schedules')
    # ### end Alembic commands ###
