"""Initial workforce schema

Revision ID: cbe632974f17
Revises: 
Create Date: 2026-09-06 18:58:56.424312

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbe632974f17'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'SUPERVISOR', 'TEAM_LEADER', 'WORKER', name='user_role_enum'), nullable=False),
    sa.Column('avatar_initials', sa.String(length=5), nullable=False),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('supervisors',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supervisors_id'), 'supervisors', ['id'], unique=False)
    op.create_index(op.f('ix_supervisors_user_id'), 'supervisors', ['user_id'], unique=True)
    op.create_table('projects',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('client', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('deadline', sa.Date(), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='project_priority_enum'), nullable=False),
    sa.Column('supervisor_id', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PLANNED', 'ACTIVE', 'ON_HOLD', 'COMPLETED', 'CANCELLED', name='project_status_enum'), nullable=False),
    sa.Column('health', sa.Enum('ON_TRACK', 'AT_RISK', 'DELAYED', name='project_health_enum'), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['supervisor_id'], ['supervisors.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_created_at'), 'projects', ['created_at'], unique=False)
    op.create_index(op.f('ix_projects_deadline'), 'projects', ['deadline'], unique=False)
    op.create_index(op.f('ix_projects_health'), 'projects', ['health'], unique=False)
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=False)
    op.create_index(op.f('ix_projects_priority'), 'projects', ['priority'], unique=False)
    op.create_index(op.f('ix_projects_start_date'), 'projects', ['start_date'], unique=False)
    op.create_index(op.f('ix_projects_status'), 'projects', ['status'], unique=False)
    op.create_index(op.f('ix_projects_supervisor_id'), 'projects', ['supervisor_id'], unique=False)
    op.create_table('teams',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('supervisor_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['supervisor_id'], ['supervisors.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_id'), 'teams', ['id'], unique=False)
    op.create_index(op.f('ix_teams_name'), 'teams', ['name'], unique=True)
    op.create_index(op.f('ix_teams_supervisor_id'), 'teams', ['supervisor_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('PROJECT_ALERT', 'BLOCKER', 'DEADLINE', 'TASK', 'WORK_UPDATE', 'TEAM_UPDATE', 'SYSTEM', name='notification_type_enum'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='notification_priority_enum'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_priority'), 'notifications', ['priority'], unique=False)
    op.create_index(op.f('ix_notifications_project_id'), 'notifications', ['project_id'], unique=False)
    op.create_index(op.f('ix_notifications_read'), 'notifications', ['read'], unique=False)
    op.create_index(op.f('ix_notifications_timestamp'), 'notifications', ['timestamp'], unique=False)
    op.create_index(op.f('ix_notifications_type'), 'notifications', ['type'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('project_activities',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('user_name', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('type', sa.Enum('PROJECT_CREATED', 'PROJECT_UPDATED', 'PROJECT_STATUS_CHANGED', 'PROJECT_ASSIGNED', 'TASK_CREATED', 'TASK_UPDATED', 'TASK_ASSIGNED', 'TASK_STATUS_CHANGED', 'TASK_COMPLETED', 'WORK_UPDATE_ADDED', 'BLOCKER_REPORTED', 'BLOCKER_RESOLVED', 'TEAM_CREATED', 'TEAM_UPDATED', 'MEMBER_ADDED', 'MEMBER_REMOVED', 'USER_CREATED', 'USER_UPDATED', name='activity_type_enum'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_activities_id'), 'project_activities', ['id'], unique=False)
    op.create_index(op.f('ix_project_activities_project_id'), 'project_activities', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_activities_timestamp'), 'project_activities', ['timestamp'], unique=False)
    op.create_index(op.f('ix_project_activities_type'), 'project_activities', ['type'], unique=False)
    op.create_index(op.f('ix_project_activities_user_id'), 'project_activities', ['user_id'], unique=False)
    op.create_table('team_leaders',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('team_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_leaders_id'), 'team_leaders', ['id'], unique=False)
    op.create_index(op.f('ix_team_leaders_team_id'), 'team_leaders', ['team_id'], unique=True)
    op.create_index(op.f('ix_team_leaders_user_id'), 'team_leaders', ['user_id'], unique=True)
    op.create_table('team_projects',
    sa.Column('team_id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('team_id', 'project_id')
    )
    op.create_table('workers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('team_id', sa.String(), nullable=True),
    sa.Column('team_leader_id', sa.String(), nullable=True),
    sa.Column('supervisor_id', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'ON_LEAVE', 'UNAVAILABLE', name='worker_status_enum'), nullable=False),
    sa.Column('active_project_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['active_project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supervisor_id'], ['supervisors.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_leader_id'], ['team_leaders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workers_active_project_id'), 'workers', ['active_project_id'], unique=False)
    op.create_index(op.f('ix_workers_id'), 'workers', ['id'], unique=False)
    op.create_index(op.f('ix_workers_status'), 'workers', ['status'], unique=False)
    op.create_index(op.f('ix_workers_supervisor_id'), 'workers', ['supervisor_id'], unique=False)
    op.create_index(op.f('ix_workers_team_id'), 'workers', ['team_id'], unique=False)
    op.create_index(op.f('ix_workers_team_leader_id'), 'workers', ['team_leader_id'], unique=False)
    op.create_index(op.f('ix_workers_user_id'), 'workers', ['user_id'], unique=True)
    op.create_table('tasks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('assignee_id', sa.String(), nullable=True),
    sa.Column('team_id', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('TODO', 'IN_PROGRESS', 'COMPLETED', 'BLOCKED', name='task_status_enum'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='project_priority_enum'), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assignee_id'], ['workers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_assignee_id'), 'tasks', ['assignee_id'], unique=False)
    op.create_index(op.f('ix_tasks_due_date'), 'tasks', ['due_date'], unique=False)
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    op.create_index(op.f('ix_tasks_priority'), 'tasks', ['priority'], unique=False)
    op.create_index(op.f('ix_tasks_project_id'), 'tasks', ['project_id'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_index(op.f('ix_tasks_team_id'), 'tasks', ['team_id'], unique=False)
    op.create_table('blockers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('task_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('reported_by_id', sa.String(), nullable=True),
    sa.Column('team_id', sa.String(), nullable=True),
    sa.Column('created_date', sa.Date(), nullable=False),
    sa.Column('resolved_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'RESOLVED', name='blocker_status_enum'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reported_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blockers_created_date'), 'blockers', ['created_date'], unique=False)
    op.create_index(op.f('ix_blockers_id'), 'blockers', ['id'], unique=False)
    op.create_index(op.f('ix_blockers_project_id'), 'blockers', ['project_id'], unique=False)
    op.create_index(op.f('ix_blockers_reported_by_id'), 'blockers', ['reported_by_id'], unique=False)
    op.create_index(op.f('ix_blockers_status'), 'blockers', ['status'], unique=False)
    op.create_index(op.f('ix_blockers_task_id'), 'blockers', ['task_id'], unique=False)
    op.create_index(op.f('ix_blockers_team_id'), 'blockers', ['team_id'], unique=False)
    op.create_table('work_updates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('worker_id', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_updates_id'), 'work_updates', ['id'], unique=False)
    op.create_index(op.f('ix_work_updates_task_id'), 'work_updates', ['task_id'], unique=False)
    op.create_index(op.f('ix_work_updates_timestamp'), 'work_updates', ['timestamp'], unique=False)
    op.create_index(op.f('ix_work_updates_worker_id'), 'work_updates', ['worker_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_work_updates_worker_id'), table_name='work_updates')
    op.drop_index(op.f('ix_work_updates_timestamp'), table_name='work_updates')
    op.drop_index(op.f('ix_work_updates_task_id'), table_name='work_updates')
    op.drop_index(op.f('ix_work_updates_id'), table_name='work_updates')
    op.drop_table('work_updates')
    op.drop_index(op.f('ix_blockers_team_id'), table_name='blockers')
    op.drop_index(op.f('ix_blockers_task_id'), table_name='blockers')
    op.drop_index(op.f('ix_blockers_status'), table_name='blockers')
    op.drop_index(op.f('ix_blockers_reported_by_id'), table_name='blockers')
    op.drop_index(op.f('ix_blockers_project_id'), table_name='blockers')
    op.drop_index(op.f('ix_blockers_id'), table_name='blockers')
    op.drop_index(op.f('ix_blockers_created_date'), table_name='blockers')
    op.drop_table('blockers')
    op.drop_index(op.f('ix_tasks_team_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_project_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_priority'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_due_date'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_assignee_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_workers_user_id'), table_name='workers')
    op.drop_index(op.f('ix_workers_team_leader_id'), table_name='workers')
    op.drop_index(op.f('ix_workers_team_id'), table_name='workers')
    op.drop_index(op.f('ix_workers_supervisor_id'), table_name='workers')
    op.drop_index(op.f('ix_workers_status'), table_name='workers')
    op.drop_index(op.f('ix_workers_id'), table_name='workers')
    op.drop_index(op.f('ix_workers_active_project_id'), table_name='workers')
    op.drop_table('workers')
    op.drop_table('team_projects')
    op.drop_index(op.f('ix_team_leaders_user_id'), table_name='team_leaders')
    op.drop_index(op.f('ix_team_leaders_team_id'), table_name='team_leaders')
    op.drop_index(op.f('ix_team_leaders_id'), table_name='team_leaders')
    op.drop_table('team_leaders')
    op.drop_index(op.f('ix_project_activities_user_id'), table_name='project_activities')
    op.drop_index(op.f('ix_project_activities_type'), table_name='project_activities')
    op.drop_index(op.f('ix_project_activities_timestamp'), table_name='project_activities')
    op.drop_index(op.f('ix_project_activities_project_id'), table_name='project_activities')
    op.drop_index(op.f('ix_project_activities_id'), table_name='project_activities')
    op.drop_table('project_activities')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_timestamp'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_project_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_priority'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_teams_supervisor_id'), table_name='teams')
    op.drop_index(op.f('ix_teams_name'), table_name='teams')
    op.drop_index(op.f('ix_teams_id'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_projects_supervisor_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_status'), table_name='projects')
    op.drop_index(op.f('ix_projects_start_date'), table_name='projects')
    op.drop_index(op.f('ix_projects_priority'), table_name='projects')
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_health'), table_name='projects')
    op.drop_index(op.f('ix_projects_deadline'), table_name='projects')
    op.drop_index(op.f('ix_projects_created_at'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_supervisors_user_id'), table_name='supervisors')
    op.drop_index(op.f('ix_supervisors_id'), table_name='supervisors')
    op.drop_table('supervisors')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
