"""execution_fields

Revision ID: e06e69fd8b2e
Revises: c44abb9df33c
Create Date: 2026-09-12 18:27:58.878521

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e06e69fd8b2e'
down_revision: Union[str, None] = 'c44abb9df33c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report_runs', sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True))
    op.add_column('report_runs', sa.Column('output_path', sa.String(), nullable=True))
    op.add_column('report_runs', sa.Column('trigger_type', sa.Enum('SCHEDULED', 'MANUAL', name='trigger_type_enum'), nullable=False, server_default='SCHEDULED'))
    op.add_column('report_runs', sa.Column('execution_key', sa.String(), nullable=True))
    
    with op.batch_alter_table('report_runs', schema=None) as batch_op:
        batch_op.create_index('uq_report_runs_schedule_slot', ['schedule_id', 'scheduled_for'], unique=True, sqlite_where=sa.text('scheduled_for IS NOT NULL'), postgresql_where=sa.text('scheduled_for IS NOT NULL'))
        batch_op.create_unique_constraint('uq_report_runs_execution_key', ['execution_key'])

    op.add_column('report_schedules', sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report_schedules', 'last_run_at')
    
    with op.batch_alter_table('report_runs', schema=None) as batch_op:
        batch_op.drop_constraint('uq_report_runs_execution_key', type_='unique')
        batch_op.drop_index('uq_report_runs_schedule_slot', sqlite_where=sa.text('scheduled_for IS NOT NULL'), postgresql_where=sa.text('scheduled_for IS NOT NULL'))
        batch_op.drop_column('execution_key')
        batch_op.drop_column('trigger_type')
        batch_op.drop_column('output_path')
        batch_op.drop_column('scheduled_for')
    # ### end Alembic commands ###
